# Hardware Pins
TRIG_LEFT = 12
ECHO_LEFT = 13
TRIG_RIGHT = 23
ECHO_RIGHT = 24

DIR_LEFT_PIN = 20
DIR_RIGHT_PIN = 21
DIR_HIGH_IS_BACKWARD = False

# PWM Configuration
PWM_FREQUENCY = 1000
PWM_CHIP = 0
PWM_CHANNEL_LEFT = 0
PWM_CHANNEL_RIGHT = 1
MAX_DUTY_CYCLE = 1.0  # Normalized
MIN_DUTY_CYCLE = 0.0

# Lidar Configuration
LIDAR_PORT = "/dev/ttyUSB0"
LIDAR_BAUDRATE = 460800
LIDAR_SCAN_TIMEOUT = 2.0
LIDAR_TARGET_FREQUENCY = 10.0
LIDAR_COLLISION_DISTANCE_M = 0.3

# Sensor Offsets (Calibration Defaults)
FRONT_BUMPER_OFFSET_X = 0.03
LIDAR_OFFSET_X = -0.30
LIDAR_OFFSET_Y = 0.0
ULTRASONIC_OFFSET_X = 0.03
ULTRASONIC_OFFSET_Y_LEFT = 0.10
ULTRASONIC_OFFSET_Y_RIGHT = -0.10

# Physics
SOUND_SPEED = 34300  # cm/s

# Collision & Safety
COLLISION_DISTANCE_CM = 30.0
OBSTACLE_INFLATION_RADIUS_M = 0.3
SENSOR_TIMEOUT_WARN_SEC = 0.5
SENSOR_TIMEOUT_STOP_SEC = 2.0
SENSOR_FAIL_SPEED_FACTOR = 0.5

# Control Loop
CONTROL_LOOP_HZ = 50
SENSOR_UPDATE_HZ = 10

# Robot Geometry
WHEEL_BASE_M = 0.20

# Recording
RECORDING_BASE_DIR = "path_recordings"

# Input
CONTROLLER_ID = 0
AXIS_LEFT_TRIGGER = 2
AXIS_RIGHT_TRIGGER = 5
BUTTON_A = 0
BUTTON_B = 1
BUTTON_X = 2
BUTTON_Y = 3
BUTTON_START = 7
