motors:
  left:
    pwm_pin: 18
    direction_pin: 27
    enable_pin: 22
  right:
    pwm_pin: 13
    direction_pin: 19
    enable_pin: 26

ultrasonic:
  front:
    trigger: 23
    echo: 24
  right:
    trigger: 25
    echo: 8
  back:
    trigger: 7
    echo: 12
  left:
    trigger: 16
    echo: 20

microwave_pin: 21
